description: >
  run newman pipeline
parameters:
  dir:
    type: string
    description: "directory of the postman configuration files"
steps:
  - run:
      environment:
        COLLECTIONS_DIR: <<parameters.dir>>
      name: Newman runner
      command: <<include(scripts/greet.sh)>>
